import type { Service, DailyStats, ServiceRanking } from '@/types'

export const mockServices: Service[] = [
  {
    id: '1',
    name: 'AI Photo Editor',
    url: 'https://ai-photo-editor.vercel.app',
    description: 'AI 기반 사진 편집 서비스',
    status: 'active',
    ga4Id: 'G-XXXXXX1',
    mixpanelToken: 'mp_token_1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '2',
    name: 'Task Automation',
    url: 'https://task-auto.vercel.app',
    description: '반복 작업 자동화 도구',
    status: 'active',
    ga4Id: 'G-XXXXXX2',
    mixpanelToken: 'mp_token_2',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    name: 'Budget Tracker',
    url: 'https://budget-tracker.vercel.app',
    description: '개인 재정 관리 앱',
    status: 'active',
    ga4Id: 'G-XXXXXX3',
    mixpanelToken: 'mp_token_3',
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '4',
    name: 'Meal Planner',
    url: 'https://meal-planner.vercel.app',
    description: '주간 식단 계획 서비스',
    status: 'active',
    ga4Id: 'G-XXXXXX4',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '5',
    name: 'Study Timer',
    url: 'https://study-timer.vercel.app',
    description: '포모도로 타이머 + 학습 기록',
    status: 'active',
    ga4Id: 'G-XXXXXX5',
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '6',
    name: 'Pet Care Log',
    url: 'https://pet-care.vercel.app',
    description: '반려동물 건강 관리',
    status: 'inactive',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '7',
    name: 'Travel Wishlist',
    url: 'https://travel-wish.vercel.app',
    description: '여행지 저장 및 계획',
    status: 'pending',
    createdAt: new Date('2024-02-03'),
    updatedAt: new Date('2024-02-03'),
  },
  {
    id: '8',
    name: 'Habit Tracker',
    url: 'https://habit-track.vercel.app',
    description: '습관 형성 도우미',
    status: 'active',
    ga4Id: 'G-XXXXXX8',
    mixpanelToken: 'mp_token_8',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: '9',
    name: 'Quick Notes',
    url: 'https://quick-notes.vercel.app',
    description: '심플 메모 앱',
    status: 'active',
    ga4Id: 'G-XXXXXX9',
    createdAt: new Date('2024-02-07'),
    updatedAt: new Date('2024-02-07'),
  },
  {
    id: '10',
    name: 'Recipe Finder',
    url: 'https://recipe-finder.vercel.app',
    description: '재료로 레시피 검색',
    status: 'active',
    ga4Id: 'G-XXXXXX10',
    mixpanelToken: 'mp_token_10',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
]

export const mockDailyStats: DailyStats[] = [
  { date: '01/27', visitors: 1200, pageViews: 3400 },
  { date: '01/28', visitors: 1450, pageViews: 4100 },
  { date: '01/29', visitors: 1380, pageViews: 3900 },
  { date: '01/30', visitors: 1520, pageViews: 4300 },
  { date: '01/31', visitors: 1680, pageViews: 4800 },
  { date: '02/01', visitors: 1890, pageViews: 5200 },
  { date: '02/02', visitors: 2100, pageViews: 5800 },
]

export const mockServiceRankings: ServiceRanking[] = [
  {
    service: mockServices[0],
    totalVisitors: 12500,
    totalPageViews: 35000,
    avgSessionDuration: 185,
    bounceRate: 42,
    trend: 15.3,
    rank: 1,
  },
  {
    service: mockServices[7],
    totalVisitors: 9800,
    totalPageViews: 28000,
    avgSessionDuration: 210,
    bounceRate: 38,
    trend: 22.1,
    rank: 2,
  },
  {
    service: mockServices[2],
    totalVisitors: 8500,
    totalPageViews: 24000,
    avgSessionDuration: 156,
    bounceRate: 45,
    trend: 8.7,
    rank: 3,
  },
  {
    service: mockServices[9],
    totalVisitors: 7200,
    totalPageViews: 20000,
    avgSessionDuration: 145,
    bounceRate: 48,
    trend: 5.2,
    rank: 4,
  },
  {
    service: mockServices[1],
    totalVisitors: 6800,
    totalPageViews: 18500,
    avgSessionDuration: 198,
    bounceRate: 41,
    trend: -2.3,
    rank: 5,
  },
  {
    service: mockServices[4],
    totalVisitors: 5500,
    totalPageViews: 15000,
    avgSessionDuration: 220,
    bounceRate: 35,
    trend: 12.4,
    rank: 6,
  },
  {
    service: mockServices[8],
    totalVisitors: 4200,
    totalPageViews: 11000,
    avgSessionDuration: 130,
    bounceRate: 52,
    trend: -5.1,
    rank: 7,
  },
  {
    service: mockServices[3],
    totalVisitors: 3800,
    totalPageViews: 9500,
    avgSessionDuration: 175,
    bounceRate: 44,
    trend: 3.8,
    rank: 8,
  },
]

export const mockTrafficSources = [
  { name: 'Direct', value: 35 },
  { name: 'Organic Search', value: 28 },
  { name: 'Social', value: 22 },
  { name: 'Referral', value: 15 },
]

export const mockServiceComparison = [
  { name: '01/27', 'AI Photo Editor': 420, 'Habit Tracker': 380, 'Budget Tracker': 320 },
  { name: '01/28', 'AI Photo Editor': 480, 'Habit Tracker': 420, 'Budget Tracker': 350 },
  { name: '01/29', 'AI Photo Editor': 510, 'Habit Tracker': 460, 'Budget Tracker': 380 },
  { name: '01/30', 'AI Photo Editor': 550, 'Habit Tracker': 520, 'Budget Tracker': 400 },
  { name: '01/31', 'AI Photo Editor': 620, 'Habit Tracker': 580, 'Budget Tracker': 420 },
  { name: '02/01', 'AI Photo Editor': 680, 'Habit Tracker': 650, 'Budget Tracker': 450 },
  { name: '02/02', 'AI Photo Editor': 750, 'Habit Tracker': 720, 'Budget Tracker': 480 },
]
